export const POST_CATEGORIES = [
    "INVESTMENTS",
    "SAVINGS",
    "DEBT",
    "FINANCIAL_EDUCATION",
    "RETIREMENT",
    "TAXES",
    "FINTECH",
    "ENTREPRENEURSHIP",
    "PERSONAL_FINANCE",
    "ECONOMY",
] as const;